name: planora
description: "Planora is a simple and easy to use planner app for Android and iOS."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  build_runner: ^2.4.15
  calendar_view: ^1.4.0
  cupertino_icons: ^1.0.8
  date_field: ^6.0.3+1
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.17
  get: ^4.7.2
  google_fonts: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  intl: ^0.20.2
  ionicons: ^0.2.2
  path_provider: ^2.1.5

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/notification.svg
    - assets/icons/home-2.svg
    - assets/icons/home-2-selected.svg
    - assets/icons/calendar.svg
    - assets/icons/calendar-selected.svg
    - assets/icons/chart-2.svg
    - assets/icons/profile.svg
    - assets/shapes/profile_card.svg
    - assets/icons/calendar_add_schedule.svg
