// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7vGPZv8UmfBtr4HK6u2Nd6yAzkQyxKZc',
    appId: '1:390158598091:web:8fdd76af240dc96bda004e',
    messagingSenderId: '390158598091',
    projectId: 'planora-np47',
    authDomain: 'planora-np47.firebaseapp.com',
    storageBucket: 'planora-np47.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2-qEyJlcwDB5yVCnthwr1O-QzVABhp6k',
    appId: '1:390158598091:android:810ca004298fdc39da004e',
    messagingSenderId: '390158598091',
    projectId: 'planora-np47',
    storageBucket: 'planora-np47.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWXi5QoeVeQvzhZZ6eS7ZyLf1oZTG6bLo',
    appId: '1:390158598091:ios:17aa585999a3d7a3da004e',
    messagingSenderId: '390158598091',
    projectId: 'planora-np47',
    storageBucket: 'planora-np47.firebasestorage.app',
    iosClientId: '390158598091-bkf6pcr4fkvbljvd5tllplgsprffvjkf.apps.googleusercontent.com',
    iosBundleId: 'com.noelpinto47.planora',
  );
}
